# Configuration file for PPG to Respiratory Waveform Estimation

# Data Configuration
data:
  csv_folder: "csv"
  input_column: "PPG"
  target_column: "NASAL CANULA"
  sampling_rate: 256
  segment_length: 2048  # 8 seconds at 256 Hz
  overlap: 0.5  # 50% overlap between segments
  
# Preprocessing Configuration
preprocessing:
  bandpass_filter:
    low_freq: 0.05  # Lower frequency for better stability
    high_freq: 2.0   # Higher frequency, well below Nyquist
    order: 2         # Lower order for better numerical stability
  downsample:
    target_rate: 64  # Downsample to 64 Hz
  normalization: "z_score"  # Options: z_score, min_max, robust

# Model Configuration
model:
  name: "CNN_LSTM"  # Options: CNN1D, LSTM, CNN_LSTM, Transformer
  input_size: 512  # After downsampling: 2048/4 = 512
  hidden_size: 128
  num_layers: 3
  dropout: 0.2
  
# Training Configuration
training:
  batch_size: 128  # Reduced batch size for stability
  learning_rate: 0.0001  # Lower learning rate to prevent instability
  max_epochs: 1
  patience: 15  # Early stopping patience
  val_split: 0.2  # 20% of training data for validation
  optimizer: "adamw"  # AdamW with weight decay for better regularization
  scheduler: "reduce_on_plateau"
  weight_decay: 1e-4  # L2 regularization
  gradient_clip_val: 1.0  # Gradient clipping
  
# Cross Validation Configuration
cross_validation:
  method: "leave_one_out"  # Leave one subject out
  
# Logging Configuration
logging:
  log_dir: "logs"
  experiment_name: "ppg_respiratory_estimation"
  save_top_k: 3
  
# Evaluation Configuration
evaluation:
  metrics: ["pearson_correlation", "mse", "mae"]
  plot_samples: 5  # Number of random samples to plot
  
# Hardware Configuration
hardware:
  accelerator: "auto"  # auto, cpu, gpu
  devices: 1
  precision: 32
